spring:
  application:
    name: carlpion
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.130.17:1521:XE
    username: C##PROJECTCP
    password: 1234
  profiles:
    include: private
  include: mail

  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:uploads/

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 200MB

server:
  port: 80

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
