<<<<<<< HEAD
spring:
  application:
    name: carlpion

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver

  profiles:
    include: private,mail


  mvc:
    static-path-pattern: /uploads/**

  web:
    resources:
      static-locations: file:uploads/

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 200MB

server:
  port: 80

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml, classpath:/mypageMapper/*.xml
=======
spring:
  application:
    name: carlpion
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
  profiles:
    include: 
      - private
      - mail
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 200MB
server:
  port: 80
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml, classpath:/mypageMapper/*.xml
>>>>>>> e49e5978f2255120b4906dddeb33e0bdde98f8f0
