spring:
  application:
    name: carlpion
<<<<<<< HEAD
  datasource:
    url: jdbc:oracle:thin:@112.221.156.34:12345:XE
    username: C##PROJECTCP
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
=======

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.130.17:1521:XE
    username: C##PROJECTCP
    password: 1234

  profiles:
    include: private

  mvc:
    static-path-pattern: 

  web:
    resources:
      static-locations:

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

>>>>>>> 378eba416fc912cf05fb1c421366f72a5ee4e167
server:
  port: 80

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: VARCHAR
  
  mapper-locations: classpath:mapper/*.xml
